---
- name: 'Install packages'
  apt: 
    name: '{{ item }}'
    update_cache: true
    cache_valid_time: 3600
    state: present
  loop:
    - mariadb-server
    - python3-pip
    - mariadb-client
  become: true
- name: 'Install pymysql module'
  pip:
    name: 'PyMySQL'
    state: present
  become: true
- name: 'Start Mariadb'
  become: true
  service: 
    name: 'mariadb'
    state: started
    enabled: true
- name: 'update mysql root password for all root accounts'
  become: true
  mysql_user: 
    name: '{{ mysql_root_user }}' 
    password: '{{ mysql_root_password }}'
    login_user: '{{ mysql_root_user }}'
    login_password: '{{ mysql_root_password }}'
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
    login_unix_socket: '{{ login_unix_socket }}'
- name: 'create mysql user'
  mysql_user:
    name: '{{ db_username }}'
    password: '{{ db_user_pass }}'
    priv: '*.*:ALL'
    login_user: '{{ mysql_root_user }}'
    login_password: '{{ mysql_root_password }}'
    login_unix_socket: '{{ login_unix_socket }}'
  become: true
- name: 'create mysql db'
  mysql_db:
    name: '{{ db_name }}'
    state: present
    login_user: '{{ mysql_root_user }}'
    login_password: '{{ mysql_root_password }}'
    login_unix_socket: '{{ login_unix_socket }}'
  become: true
